### PR TITLE
add coming soon component and content

### PR DESCRIPTION
**Pull request by cezarneaga**
- [x] SidebarLeft styles should be applied when using the `<Layout left={<SidebarLeft />}>` not by adding class styles to bodyClass
- [x] SidebarLeft should also allow for no content in it

### CODE REVIEW

**Comment by cezarneaga** [comment]
SidebarLeft types ar putea fi de tip boolean sau object. daca e boolean sidebar apare dar e gol.

**Comment by st3phan-cs** [comment]
@cezarneaga 
Poti sa folosesti sub forma de mai jos:
`<Layout left={true} right={true}>`

**Comment by cezarneaga** [comment]
s-a stricat css. vezi homepage

**Comment by st3phan-cs** [comment]
> s-a stricat css. vezi homepage

Fixat.

**Pull request merged**
